# Generated by Django 5.1.7 on 2025-05-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unique_user_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
